version: '3.8'

services:
  apteka_postgres:
    image: postgres:15
    container_name: apteka_db
    environment:
      POSTGRES_DB: apteka_db
      POSTGRES_USER: adminka
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  php:
    image: yiisoftware/yii2-php:8.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - apteka_postgres
    # ТРИ КОМАНДЫ: установка зависимостей, права, миграции
    command: >
      sh -c "
      composer install --ignore-platform-reqs &&
      chmod -R 777 runtime web/assets &&
      php yii migrate --interactive=0 &&
      apache2-foreground
      "

volumes:
  postgres_data:
