services:
  apteka_postgres:
    image: postgres:15
    container_name: apteka_db
    environment:
      POSTGRES_DB: apteka_db
      POSTGRES_USER: adminka
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminka -d apteka_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  php:
    image: yiisoftware/yii2-php:8.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      apteka_postgres:
        condition: service_healthy
    working_dir: /app
    environment:
      - PHP_IDE_CONFIG=serverName=docker
      - YII_ENV=dev
      - YII_DEBUG=true
    command: >
      sh -c "
      composer install --ignore-platform-reqs &&
      chmod -R 777 runtime web/assets &&
      php yii migrate --interactive=0 &&
      apache2-foreground
      "
volumes: 
  postgres_data:
